name: mp-stats-legacy-viewer
description: MP Stats Legacy Viewer
version: 1.0.5
appVersion: v0.14.0
apiVersion: v2
home: https://github.com/TimSchoenle/helm-charts
sources:
  - https://github.com/TimSchoenle/mp-stats-legacy-viewer
maintainers:
  - name: Tim Schönle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: 1.0.3
    repository: "file://../common"