name: mp-stats-legacy-viewer
description: MP Stats Legacy Viewer
version: 2.0.0
appVersion: v0.15.0
apiVersion: v2
home: https://github.com/TimSchoenle/helm-charts
sources:
  - https://github.com/TimSchoenle/mp-stats-legacy-viewer
maintainers:
  - name: Tim Schönle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: 1.4.0
    repository: "file://../common"