apiVersion: v2
name: common
description: Shared template partials for the TimSchoenle Helm charts
type: library
version: 2.4.0
home: https://github.com/TimSchoenle/helm-charts
sources:
  - https://github.com/TimSchoenle/helm-charts
maintainers:
  - name: Tim Schönle
    url: https://github.com/TimSchoenle
