#!/usr/bin/env python3
"""The credential reference each chart's README carries, written from the contract.

A chart that mounts credentials as files has to tell an operator three things: which credentials
the image needs, what to name the keys of the Secret that carries them, and which environment
spelling addresses the same value. All three are published by the image — `secrets_file`, `env`
and `env_file` per key, with `required` and the producer's own summary beside them — and all
three were transcribed into every README by hand.

The transcription drifts, and it drifts silently, because nothing downstream reads a README.
`tankovault` is the measured case: its table listed seven credentials against the sixteen its nine
contracts declare, spelt one of them under a name no contract carries, and marked another
required that only one service requires. Every one of those was true when it was written.

So the rows come from the contract now, and the block is regenerated by `just config-readme` the
way `values.schema.json` and every chart README already are. What stays hand-written is the one
column no contract can fill: *when this chart needs the credential*. That is chart knowledge —
`services.sync.enabled`, `storage.backend: postgres`, "first install only" — and it lives in
`config-contract.yaml` beside the keys it describes, where a note for a credential the image
stopped declaring is refused rather than left standing.

--------------------------------------------------------------------------------------------
Where the block goes
--------------------------------------------------------------------------------------------

Between two HTML comments in the chart's `README.md.gotmpl`:

    <!-- @config-credentials -->
    ...generated...
    <!-- @config-credentials end -->

In the `.gotmpl` rather than in the rendered `README.md`, because helm-docs regenerates the second
from the first on every pull request and would overwrite anything written there. HTML comments
rather than a marker of this repository's own, because they survive the round trip through
helm-docs and through every Markdown renderer that publishes the result, and a reader of the
published page sees nothing.

The chart chooses *where* the block sits; this module owns only what is between the markers. A
chart whose contracts declare a credential and which carries no block is a failure rather than a
skip — the whole point is that the reference cannot be forgotten — and a block in a chart with no
credential is a failure for the mirror reason.

--------------------------------------------------------------------------------------------
What is deliberately not generated
--------------------------------------------------------------------------------------------

**The `kubectl create secret` example.** It carries a Secret name, a namespace placeholder and,
for several charts, an `openssl rand` line whose length is the chart's own decision. None of that
is in a contract, and a generated example is one nobody has checked against the chart's own
`existingSecret` prose two paragraphs above.

**Everything a credential means.** The producer's summary is one line and it is rendered; the
paragraph explaining what losing `auth__password_pepper` costs is the chart's, and it stays in the
chart's prose.

Usage: .github/scripts/config_readme.py [--charts DIR] [--check]
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import yaml

import config_contract as cc
from config_bindings import has_path
from config_declaration import Declaration, DeclarationError, union_for
from config_paths import CHARTS_DIR
from config_secrets import Credential, contracted_charts, credentials, declared_secrets

# The two comments the generated block sits between. Read as whole lines with their indentation
# ignored, so a chart may sit them inside a list item without the parser caring.
OPEN = "<!-- @config-credentials -->"
CLOSE = "<!-- @config-credentials end -->"

TEMPLATE = "README.md.gotmpl"


class ReadmeError(Exception):
    """A README this module cannot write its block into."""


def env_prefix(chart_dir: Path, declaration: Declaration) -> str:
    """The variable prefix every document of one chart agrees on, or `""` when they do not.

    Taken from the contract's own dialect rather than guessed from the longest common prefix of
    the spellings, which is what the inventory used to do and which reads as
    `MP_STATS_TELEMETRY__SENTRY__DSN` on a chart with exactly one credential — the whole variable,
    presented as the prefix.
    """
    prefixes = set()
    for document in declaration.documents:
        try:
            prefixes.add(union_for(chart_dir, document).prefix)
        except cc.ContractError:
            return ""
    return prefixes.pop() if len(prefixes) == 1 else ""


def block_for(
    chart_dir: Path, declaration: Declaration, rows: list[Credential], values: dict
) -> list[str]:
    """The generated credential reference for one chart, as the lines between the markers."""
    notes = dict(declaration.credentials)
    unknown = sorted(set(notes) - {row.path for row in rows})
    if unknown:
        raise ReadmeError(
            f"{declaration.path}: `credentials` carries an entry for "
            f"{', '.join(repr(key) for key in unknown)}, which no contract this chart declares "
            "marks `secret: true` — the entry has outlived the credential it described"
        )

    missing = sorted(
        entry.value
        for entry in notes.values()
        if entry.value is not None and not has_path(values, entry.value)
    )
    if missing:
        raise ReadmeError(
            f"{declaration.path}: `credentials` names the chart value(s) "
            f"{', '.join(repr(name) for name in missing)}, which this chart's values.yaml does "
            "not expose — a renamed value leaves the reference telling operators to set "
            "something that does nothing"
        )

    # Each optional column appears only where it carries something. `Read by` on a
    # single-document chart would be that chart's own name repeated once per row, and an empty
    # column is one more thing between an operator and the key name they came for.
    multi = len(declaration.documents) > 1
    valued = any(entry.value for entry in notes.values())
    annotated = any(entry.note for entry in notes.values())

    columns = ["Secrets file", "Required"]
    if valued:
        columns.append("Chart value")
    if multi:
        columns.append("Read by")
    if annotated:
        columns.append("When")

    lines = [
        "Every credential below is read from a **file in the secrets directory**, named for the",
        "configuration path it carries with `.` written as `__`. A file spelt any other way is",
        "mounted and never read. Those names are the keys of the Secret this chart mounts, except",
        "where a note below says otherwise.",
        "",
        "| " + " | ".join(columns) + " |",
        "|" + "|".join(["---"] * len(columns)) + "|",
    ]

    for row in rows:
        entry = notes.get(row.path)
        cells = [f"`{row.secrets_file}`", "yes" if row.required else "no"]
        if valued:
            cells.append(f"`{entry.value}`" if entry and entry.value else "")
        if multi:
            cells.append(", ".join(f"`{name}`" for name in row.documents))
        if annotated:
            cells.append(entry.note if entry and entry.note else "")
        lines.append("| " + " | ".join(cells) + " |")

    prefix = env_prefix(chart_dir, declaration)
    if prefix:
        lines.extend(
            [
                "",
                f"The same value is addressable as the variable `{prefix}<PATH>`, upper-cased "
                "with `.`",
                "written as `__`, and that spelling with `_FILE` appended names a file whose "
                "contents",
                "supply it.",
            ]
        )

    return lines


def splice(text: str, block: list[str], where: str) -> str:
    """One README template with the block between its markers replaced.

    The markers are matched as whole lines and their own indentation is preserved, so the block a
    chart nests inside a list item stays nested. Anything but exactly one pair is refused: a
    second pair would make "the block" ambiguous, and an unclosed one would swallow the rest of
    the file.
    """
    ending = "\r\n" if text.count("\r\n") else "\n"
    lines = text.split(ending)

    opens = [number for number, line in enumerate(lines) if line.strip() == OPEN]
    closes = [number for number, line in enumerate(lines) if line.strip() == CLOSE]
    if len(opens) != 1 or len(closes) != 1:
        raise ReadmeError(
            f"{where}: carries {len(opens)} `{OPEN}` and {len(closes)} `{CLOSE}` markers, and a "
            "generated block is delimited by exactly one of each"
        )
    if closes[0] < opens[0]:
        raise ReadmeError(f"{where}: the `{CLOSE}` marker sits above the `{OPEN}` one")

    indent = lines[opens[0]][: len(lines[opens[0]]) - len(lines[opens[0]].lstrip())]
    body = [f"{indent}{line}" if line else "" for line in block]
    lines[opens[0] + 1 : closes[0]] = body
    return ending.join(lines)


def carries_markers(text: str) -> bool:
    return any(line.strip() == OPEN for line in text.splitlines())


def walk(charts: Path, check: bool) -> tuple[list[str], int]:
    """Every contracted chart's block, written or compared. Returns the problems and the count."""
    problems: list[str] = []
    touched = 0

    for chart_dir, declaration in contracted_charts(charts):
        template = chart_dir / TEMPLATE
        rows = credentials(declared_secrets(chart_dir, declaration))

        if not template.is_file():
            if rows:
                problems.append(
                    f"{chart_dir.name}: declares {len(rows)} credential(s) and has no "
                    f"{TEMPLATE} to write the reference into"
                )
            continue

        with template.open(encoding="utf-8", newline="") as handle:
            text = handle.read()

        if not carries_markers(text):
            if rows:
                problems.append(
                    f"{template}: this chart's contracts declare {len(rows)} credential(s) and "
                    f"the template carries no `{OPEN}` block for them. Add the two markers where "
                    "the reference belongs and run `just config-readme`"
                )
            continue

        if not rows:
            problems.append(
                f"{template}: carries a `{OPEN}` block and no contract this chart declares marks "
                "any key `secret: true`, so there is nothing to generate into it"
            )
            continue

        try:
            values = yaml.safe_load((chart_dir / "values.yaml").read_text(encoding="utf-8")) or {}
            block = block_for(chart_dir, declaration, rows, values)
            updated = splice(text, block, str(template))
        except (ReadmeError, DeclarationError) as failure:
            problems.append(str(failure))
            continue

        if updated == text:
            continue

        if check:
            difference = "\n".join(
                difflib.unified_diff(
                    text.splitlines(),
                    updated.splitlines(),
                    fromfile=str(template),
                    tofile="the contract",
                    lineterm="",
                )
            )
            problems.append(
                f"{template}: the credential reference is not what the contract describes; run "
                f"`just config-readme`\n{difference}"
            )
            continue

        with template.open("w", encoding="utf-8", newline="") as handle:
            handle.write(updated)
        touched += 1

    return problems, touched


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--charts", default=CHARTS_DIR, type=Path, help="charts directory (default: charts)"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a generated reference is behind its contract, rather than writing it",
    )
    args = parser.parse_args(argv)

    if not args.charts.is_dir():
        print(f"error: {args.charts} is not a directory", file=sys.stderr)
        return 1

    try:
        problems, touched = walk(args.charts, args.check)
    except (DeclarationError, cc.ContractError) as failure:
        print(f"error: {failure}", file=sys.stderr)
        return 1

    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        print(f"\nerror: {len(problems)} credential reference problem(s)", file=sys.stderr)
        return 1

    if args.check:
        print("==> every credential reference is current")
    elif touched:
        print(f"==> rewrote {touched} credential reference(s)")
    else:
        print("==> every credential reference already matches its contract")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
