apiVersion: v2
name: cloudflare-access-webhook-redirect
description: A Helm chart for deploying the Cloudflare Access Webhook Redirect service. This service acts as an authentication proxy that validates requests using Cloudflare Access Service Auth tokens before forwarding them to target backend services.
type: application
version: 6.2.3
kubeVersion: ">=1.28.0-0"
appVersion: v2.3.0
keywords:
  - cloudflare
  - webhook
  - redirect
  - authentication
annotations:
  artifacthub.io/license: MIT
home: https://github.com/TimSchoenle/cloudflare-access-webhook-redirect
sources:
  - https://github.com/TimSchoenle/cloudflare-access-webhook-redirect
  - https://github.com/TimSchoenle/helm-charts
maintainers:
  - name: Tim Schönle
    url: https://github.com/TimSchoenle
dependencies:
  - name: common
    version: 2.4.1
    repository: "file://../common"