{{- if (include "common.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  webHook: {{ required "env.webHook is required unless existingSecret is set" .Values.env.webHook | quote }}
{{- end }}
