name: %%CHART%%
description: %%DESCRIPTION%%
version: 0.1.0
appVersion: "%%APP_VERSION%%"
apiVersion: v2
home: https://github.com/TimSchoenle/helm-charts
sources:
  - %%SOURCE%%
maintainers:
  - name: Tim Schönle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: %%COMMON_VERSION%%
    repository: "file://../common"
