{{- $specs := include "tankovault.serviceSpecs" . | fromYaml -}}
{{- range $service, $spec := $specs }}
{{- if (index $.Values.services $service).enabled }}
---
{{ include "tankovault.service" (dict "ctx" $ "service" $service) }}
{{- end }}
{{- end }}
