{{- include "tankovault.validateValues" . }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tankovault.serviceAccountName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- $annotations := merge (deepCopy .Values.serviceAccount.annotations) (deepCopy .Values.commonAnnotations) }}
  {{- with $annotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
