name: portfolio
description: Personal portfolio built with Rust (Yew frontend, Axum server).
version: 2.0.0
appVersion: v2.1.0
apiVersion: v2
home: https://github.com/TimSchoenle/helm-charts
sources:
  - https://github.com/TimSchoenle/Portfolio
maintainers:
  - name: Tim Schönle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: 0.1.2
    repository: "file://../common"