apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with (include "common.updateStrategy" (dict "ctx" . "rwo" false)) }}
  strategy:
    {{- . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with (include "common.podAnnotations" (dict "ctx" $ "templates" (list "configmap.yaml"))) }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.podLabels" . | nindent 8 }}
    spec:
      {{- include "common.podSpec.common" . | nindent 6 }}
      containers:
        {{- include "common.container" (dict
              "ctx" $
              "ports" (list (dict "name" "http" "containerPort" (int .Values.application.port) "protocol" "TCP"))
              "envFrom" (list (dict "configMapRef" (dict "name" (include "common.fullname" .))))
            ) | nindent 8 }}
      {{- with (include "common.volumes" (dict "ctx" $)) }}
      volumes:
        {{- . | nindent 8 }}
      {{- end }}
