{{- include "common.validateValues" (dict "ctx" $ "required" (list
     "application.server.host"
     "application.server.port"
     "application.handler.targetBase"
   )) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  SERVER.HOST: {{ .Values.application.server.host | quote }}
  SERVER.PORT: {{ .Values.application.server.port | quote }}
  WEBHOOK.TARGET_BASE: {{ .Values.application.handler.targetBase | quote }}
  WEBHOOK.PATHS: {{ include "config.paths" . }}
  LOG_LEVEL: {{ .Values.application.logLevel | quote }}
  {{- with .Values.application.sentryDsn }}
  SENTRY_DSN: {{ . | quote }}
  {{- end }}


{{/*
Convert path values to the correct format
Example: api/webhook:ALL; test:GET,POST
*/}}
{{- define "config.paths" -}}
{{- $list := list -}}
{{- range $k, $v := .Values.application.handler.paths -}}
{{- $list = append $list (printf "%s:%s" $k (join "," $v)) -}}
{{- end -}}
{{ join "; " $list }}
{{- end -}}