webhook:
  targetBase: "https://test.google.com"
  paths:
    "/api/webhook/.*":
      - ALL

cloudflare:
  clientId: "testId"
  clientSecret: "testSecret"

networkPolicy:
  enabled: true
  egress:
    enabled: true
    https:
      enabled: true
