webhook:
  targetBase: "https://test.google.com"
  paths:
    "/api/webhook/.*":
      - ALL

cloudflare:
  clientId: "testId"
  clientSecret: "testSecret"

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable: null
