name: netcup-offer-bot
description: This chart deploys the Netcup Offer Bot, which monitors https://www.netcup-sonderangebote.de/ RSS feed and sends notifications to Discord webhooks when new offers are available.
version: 6.1.2
appVersion: v3.1.0
apiVersion: v2
home: https://github.com/TimSchoenle/helm-charts
sources:
  - https://github.com/TimSchoenle/netcup-offer-bot
maintainers:
  - name: Tim Schönle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: 2.4.0
    repository: "file://../common"