name: Auto-Rebase PRs on Push to Main

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  auto-rebase:
    name: Auto-Rebase
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-rebase.yaml@6d60e35ef5ff9a9c330dc56d134c056795154dfd # workflows-maintenance-auto-rebase-v1.1.2
    secrets:
      app_id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
      private_key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
    with:
      label: 'auto-rebase'