name: Auto-Rebase PRs on Push to Main

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  auto-rebase:
    name: Auto-Rebase
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-rebase.yaml@6f1b6457cb8dfdf07c03e691c43dd3ecc20c8a2c # workflows-maintenance-auto-rebase-v1.1.1
    secrets:
      app_id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
      private_key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
    with:
      label: 'auto-rebase'