name: Auto-Rebase PRs on Push to Main

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  auto-rebase:
    name: Auto-Rebase
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-rebase.yaml@43af44486f5d94a5438695ee2918d276852f9db5 # tag=workflows-maintenance-auto-rebase-v1.1.6
    secrets:
      app_id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
      private_key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
    with:
      label: 'auto-rebase'