name: "PR Labeler"

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  auto-label:
    name: Auto Label
    permissions:
      contents: read # To read labels
      pull-requests: write # To add labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"