name: Release Charts

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  release:
    name: Release Charts
    runs-on: ubuntu-latest
    permissions:
      contents: write # to publish chart releases
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Generate Bot Token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ steps.generate_token.outputs.token }}

      - name: Configure Git
        uses: TimSchoenle/actions/actions/common/setup-app-git-identity@2b241369e824822cae66f889c9b7e589538471f6 # tag=actions-common-setup-app-git-identity-v1.3.0
        with:
          app-slug: ${{ steps.generate_token.outputs.app-slug }}
          token: ${{ steps.generate_token.outputs.token }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          # We currently can't use a passphrase since this means we can't export the key to the legacy format
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Export GPG key to legacy format
        run: gpg --export-secret-keys > ~/.gnupg/pubring.gpg

      - name: Setup Helm Environment
        uses: ./.github/actions/setup-helm

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          config: ./.github/configs/cr.yaml
        env:
          CR_TOKEN: ${{ steps.generate_token.outputs.token }}